# SVM

Here is the code for running SVM in python using the sklearn's SVM function. Some of the code is based on the following references:
https://scikit-learn.org/stable/modules/svm.html

https://www.datacamp.com/tutorial/svm-classification-scikit-learn-python

First, import the required libraries.

In [ ]:
import pandas as pd
import numpy as np
from sklearn import svm

We then upload our files to Google Colab and then read the files to objects.

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv
Saving test.csv to test.csv


In [ ]:
import io
train = pd.read_csv(io.BytesIO(uploaded['train.csv']))
test = pd.read_csv(io.BytesIO(uploaded['test.csv']))

In [ ]:
train.shape

(63, 2309)

In [ ]:
test.shape

(20, 2309)

Now we are ready to separate the files to training and test inputs and outputs.

In [ ]:
trainIn = np.array(train[train.columns[:2308]])
testIn = np.array(test[test.columns[:2308]])
trainOut = np.array(train[train.columns[-1]])
testOut = np.array(test[test.columns[-1]])

Now we will create our model. Given that our target variable has multiple classes (4 in this case), we need to use an approach for the classification. The choices are “one-versus-one” classifier (ovo) or a “one-vs-rest” (ovr) classifier.

In [ ]:
model = svm.SVC(kernel = 'linear', decision_function_shape='ovo')
model.fit(trainIn, trainOut)


SVC(decision_function_shape='ovo', kernel='linear')

We can find the support vectors as:

In [ ]:
model.support_vectors_

array([[-1.940027  , -2.877061  ,  0.07129688, ..., -1.667067  ,
        -0.1150742 , -1.524637  ],
       [-1.051824  , -2.887775  ,  0.6408534 , ..., -1.31565   ,
        -0.310746  , -2.054944  ],
       [-0.9686372 , -2.748872  ,  0.3336826 , ..., -1.126395  ,
        -0.4546028 , -1.306006  ],
       ...,
       [ 0.8025844 ,  0.6547701 , -1.223156  , ..., -0.9088187 ,
        -0.2203973 , -1.504628  ],
       [ 0.2442003 , -0.2523149 , -1.508688  , ..., -0.9258361 ,
        -0.01836766, -0.7758768 ],
       [ 0.7079373 , -0.347149  ,  0.0429637 , ..., -1.180908  ,
        -1.338648  , -1.085005  ]])

And we can make predictions for the test set as:

In [ ]:
model.predict(testIn)

array([3, 2, 4, 2, 1, 3, 4, 2, 3, 1, 3, 4, 1, 2, 2, 2, 4, 2, 4, 2])

We can now calculate the accuracy as:

In [ ]:
np.mean(model.predict(testIn) == testOut)

0.9

We can also derive the probabilistic class assignments if we set the option 'probability' to True:

In [ ]:
model2 = svm.SVC(kernel = 'linear', decision_function_shape='ovo', probability = True)
model2.fit(trainIn, trainOut)

SVC(decision_function_shape='ovo', kernel='linear', probability=True)

In [ ]:
model2.predict_proba(testIn)

array([[0.05869296, 0.21139503, 0.6335112 , 0.0964008 ],
       [0.06138994, 0.82664247, 0.03735719, 0.0746104 ],
       [0.01454174, 0.01278059, 0.01390147, 0.95877619],
       [0.01532097, 0.94582162, 0.01547315, 0.02338426],
       [0.83357368, 0.10087632, 0.02623055, 0.03931946],
       [0.02566894, 0.05343244, 0.87267462, 0.048224  ],
       [0.01532396, 0.26223344, 0.02979285, 0.69264975],
       [0.02263341, 0.86620546, 0.01998085, 0.09118028],
       [0.0288187 , 0.24498246, 0.58997703, 0.1362218 ],
       [0.7964549 , 0.0976332 , 0.03780565, 0.06810625],
       [0.02636243, 0.29710141, 0.5041141 , 0.17242206],
       [0.01060791, 0.01684477, 0.0119409 , 0.96060642],
       [0.79065563, 0.12089681, 0.05053287, 0.03791469],
       [0.0146361 , 0.96141625, 0.00850026, 0.01544738],
       [0.01762794, 0.8462445 , 0.02025771, 0.11586986],
       [0.01435117, 0.95715917, 0.01193454, 0.01655511],
       [0.02124697, 0.03647782, 0.02700251, 0.9152727 ],
       [0.02928702, 0.47293329,

There is also an option for giving more importance to some samples if the data is unbalanced.

In [ ]:
model3 = svm.SVC(kernel = 'linear', decision_function_shape='ovo', probability = True, class_weight='balanced')
model3.fit(trainIn, trainOut)

SVC(class_weight='balanced', decision_function_shape='ovo', kernel='linear',
    probability=True)

In [ ]:
model3.predict(testIn)

array([3, 2, 4, 2, 1, 3, 4, 2, 3, 1, 3, 4, 1, 2, 2, 2, 4, 2, 4, 2])

In [ ]:
np.mean(model3.predict(testIn) == testOut)

0.9

In our case, this doesn't impact the accuracy.

Generally, SVM is more suitable for classification problems, but it can also be used for regression (numerical output variable). *sklearn* allows for regression modeling as well. You would need to use svm.SVR() (instead of svm.SVC).